sudo: false
language: python
install:
- pip install tox
script: tox
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: blopker
  password:
    secure: SqEtl+qj+brTvcfSQeZxsemGadsEzTYki44hhyvZtAP7fBjn5kZ8ecltctpxPwcf/QZBTS1elzCcRCmSA29C3QtN1C4OJl9WBbz78wQlQELKQvy+NkX7x/C1WRVZmhQ3g5tI0zKOSobUvEbXsva00I6gyfFnYfD/m2XsyNOo3qQ/Lj7Ne8fN1CDEOh4fntJZAv2Va8Qz4Uw3v4JaxrxMnAkH52la5mn+09ZpnicDrnKFyTve1cpDAYnOFqR0h8uqHK6WZQaQnOHo3iFufKqekHX7aWQJY9LWgkHjW0KoxONFbpTCdUqX/KuMv4Mttklat98byDTmkj07UvUHNym2K13XKeCCHM/kDctoOFLAjWBjh3DR55iSRqlIKkNmrYwCF1ZXON+kD70cesGsF4BRIr84UN5VK23Q0o7PM4A9MVs0EgQVNEneCn8QBxmkuzPbWaYJRXxk4HI0CGeRbIpQIigVu3fHM2/YYq344ABP4yco7Hxj+wHn13gmeucLyd4jVBsAjGkboIz17jjW4cSKVfWAyeWFzhkX81D/xQVDM/iAn16vq6Skmax4bPPAwNnfwkM6MLjXY88OFfHfcLGqHGeUAOWqiZFKkhZAzEOfobKqzLHFy2qeMfbftMfTPQZJpdzO9riyPxoaTfaw2u8dOSdvvsmxXOOOAak2Ksyc/wU=
  on:
    tags: true
